### PR TITLE
fix for issue #35

### LINKED ISSUE #35: Generators fail to generate templates in windows
### Expected behavior

Generator should generate corresponding templates in commandline 
`choo generate page newpage`  or
`choo generate element newElement`
should trigger generator build
### Actual behavior

generator fails to generate templates but rather it throws an error in windows console. 

```
C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\bin\choo-generate.js:36
  throw e
  ^
AssertionError: Trying to copy from a source that does not exist: C:\Users\rolly_000\WebstormProjects\CWCSProject\client\elements\C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli
\generators\element\template.js
    at EditionInterface.exports._copySingle (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\copy.js:45:3)
    at EditionInterface.exports.copy (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\copy.js:23:17)
    at EditionInterface.module.exports [as move] (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\mem-fs-editor\lib\actions\move.js:4:8)
    at mv (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\utils.js:35:28)
    at generate (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\utils.js:38:3)
    at Object.module.exports [as element] (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\generators\element\index.js:8:3)
    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\bin\choo-generate.js:33:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\exec.js:10
      throw new Error('Error code: ' + code)
      ^

Error: Error code: 1
    at ChildProcess.exec.on.code (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\lib\exec.js:10:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Program Files (x86)\Nodist\bin\node_modules\choo-cli\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```
### Steps to reproduce behavior

enter choo generate command in command line e.g
`choo generate page newPage`

### PR DESCRIPTION
**Pull request by rollymaduk**
Fixed #35 ,  template bug on windows OS caused by differences on how OS reads file paths. Hope this helps

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -6,6 +6,7 @@ const resolvePath = require('path').resolve
 const once = require('ramda').once
 const walkBack = require('walk-back')
 const chalk = require('chalk')
+const delim=(require('os').platform()==='win32')? '\\' :'/'
```
Comment (YerkoPalma) [inline lib/utils.js]: This line is breaking standard style. I guess it should be like this

``` javascript
const delim = (require('os').platform() === 'win32') ? '\\' :'/'
```

Please check it.

Comment (rollymaduk) [reply lib/utils.js]: fixed spacing issue

**Comment by YerkoPalma** [comment]
@MattMcFarland Please check this, and publish to npm when done
